# Generated by Django 4.0 on 2022-01-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ombor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('dokon_nomi', models.CharField(max_length=100)),
                ('turi', models.CharField(blank=True, max_length=30)),
                ('manzil', models.CharField(max_length=100)),
                ('tel', models.SmallIntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('brend_nomi', models.CharField(max_length=100)),
                ('narx', models.IntegerField()),
                ('miqdor', models.IntegerField()),
                ('ombor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skladapp.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokon_nomi', models.CharField(max_length=100)),
                ('manzil', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=15)),
                ('ism', models.CharField(max_length=30)),
                ('qarz', models.IntegerField(default=0)),
                ('ombor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skladapp.ombor')),
            ],
        ),
    ]
