# Generated by Django 4.0 on 2022-01-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skladapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='narx',
            new_name='kelgan_narx',
        ),
        migrations.AddField(
            model_name='product',
            name='sotuvdagi_narx',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
